runtime: python
env: flex
# entrypoint: gunicorn -b :$PORT Index:app.server -w 2 --timeout 1000
entrypoint: python Index.py
runtime_config:
  python_version: 3
manual_scaling:
  instances: 1
resources:
  cpu: 8
  memory_gb: 15
  disk_size_gb: 10